#!/usr/bin/env python3
"""Regenerate program-state.md, the single-file bundle of all program documents
plus verification scripts, for upload to the claude.ai project knowledge.
Run after any session that changes program state: python3 make_bundle.py
"""
import datetime, pathlib

DOCS = [
    "roadmap.md", "citations.md", "lemma-0-sandwich.md", "lemma-A-small-primes.md",
    "lemma-B-anatomy-independence.md", "lemma-C-within-side.md", "lemma-D-cross-side.md",
    "prop-deep-large-sieve.md", "numerology-D.md", "empirics-D.md", "lemma-alpha-beta.md",
    "wp21-reduction.md", "wp22-minor-major.md", "wp23-anatomy.md", "wp24-e1-e2-fineclass.md", "wp5-diagnosis.md", "wp3-lemma-C-diagnosis.md",
]
SCRIPTS = ["verify_dls.py", "wp21_test.py", "empirics_d.py", "e1_probe.py", "e2_probe.py", "fine_class_probe.py", "wp5_witness_scan.py", "lemma_c_probe.py"]
SEP = "=" * 78

today = datetime.date.today().strftime("%B %-d, %Y")
out = [
    "# PROGRAM STATE — n(n-1) | C(2n,n) — consolidated bundle",
    "",
    f"Generated {today}. Single-file bundle of all {len(DOCS)} program documents plus verification scripts.",
    "Upload THIS ONE FILE to project knowledge; replace it after sessions that change state.",
    "The canonical source is the git repo (~/erdos396); this bundle is generated by make_bundle.py — never edit it directly.",
    "",
    "## Table of contents",
    "",
]
out += [f"{i+1}. {d}" for i, d in enumerate(DOCS)]
out += [f"{len(DOCS)+i+1}. {s} (appendix {chr(65+i)})" for i, s in enumerate(SCRIPTS)]
out.append("")

for d in DOCS:
    out += ["", "", SEP, f"# FILE: {d}", SEP, "", pathlib.Path(d).read_text().rstrip()]
for i, s in enumerate(SCRIPTS):
    out += ["", "", SEP, f"# APPENDIX {chr(65+i)}: {s}", SEP,
            "```python", pathlib.Path(s).read_text().rstrip(), "```"]
out.append("")

pathlib.Path("program-state.md").write_text("\n".join(out))
print(f"program-state.md regenerated: {len(DOCS)} docs + {len(SCRIPTS)} scripts, "
      f"{len('\n'.join(out))} chars")
